# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1390, 875)
        MainWindow.setMouseTracking(True)
        MainWindow.setAccessibleName("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(12, 12, 12);\n"
"color: rgb(255, 255, 255);\n"
"")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Main = QtWidgets.QGroupBox(self.centralwidget)
        self.Main.setEnabled(True)
        self.Main.setGeometry(QtCore.QRect(9, 9, 1361, 821))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.Main.sizePolicy().hasHeightForWidth())
        self.Main.setSizePolicy(sizePolicy)
        self.Main.setMinimumSize(QtCore.QSize(1344, 759))
        self.Main.setBaseSize(QtCore.QSize(0, 0))
        self.Main.setObjectName("Main")
        self.groupBox = QtWidgets.QGroupBox(self.Main)
        self.groupBox.setGeometry(QtCore.QRect(994, 760, 281, 51))
        self.groupBox.setStyleSheet(" QGroupBox {\n"
"    background-color: white;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.right_button = QtWidgets.QPushButton(self.groupBox)
        self.right_button.setGeometry(QtCore.QRect(140, 11, 37, 33))
        self.right_button.setStyleSheet("QPushButton { background-color: white; }")
        self.right_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/Rarrw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.right_button.setIcon(icon)
        self.right_button.setIconSize(QtCore.QSize(25, 25))
        self.right_button.setObjectName("right_button")
        self.left_button = QtWidgets.QPushButton(self.groupBox)
        self.left_button.setGeometry(QtCore.QRect(97, 11, 37, 33))
        self.left_button.setStyleSheet("QPushButton { background-color: white; }")
        self.left_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/larrw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_button.setIcon(icon1)
        self.left_button.setIconSize(QtCore.QSize(25, 25))
        self.left_button.setObjectName("left_button")
        self.up_button = QtWidgets.QPushButton(self.groupBox)
        self.up_button.setGeometry(QtCore.QRect(11, 11, 37, 33))
        self.up_button.setStyleSheet("QPushButton { background-color: white; }")
        self.up_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/uparrw-Copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.up_button.setIcon(icon2)
        self.up_button.setIconSize(QtCore.QSize(25, 25))
        self.up_button.setObjectName("up_button")
        self.down_button = QtWidgets.QPushButton(self.groupBox)
        self.down_button.setGeometry(QtCore.QRect(54, 11, 37, 33))
        self.down_button.setStyleSheet("QPushButton { background-color: white; }")
        self.down_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/dwnarrw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.down_button.setIcon(icon3)
        self.down_button.setIconSize(QtCore.QSize(25, 25))
        self.down_button.setObjectName("down_button")
        self.zoom_out = QtWidgets.QPushButton(self.groupBox)
        self.zoom_out.setGeometry(QtCore.QRect(183, 11, 37, 33))
        self.zoom_out.setStyleSheet("QPushButton { background-color: white; }")
        self.zoom_out.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/zoomout.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_out.setIcon(icon4)
        self.zoom_out.setIconSize(QtCore.QSize(25, 25))
        self.zoom_out.setObjectName("zoom_out")
        self.zoom_in = QtWidgets.QPushButton(self.groupBox)
        self.zoom_in.setGeometry(QtCore.QRect(226, 11, 37, 33))
        self.zoom_in.setStyleSheet("QPushButton { background-color: white; }")
        self.zoom_in.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/zoomin.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_in.setIcon(icon5)
        self.zoom_in.setIconSize(QtCore.QSize(25, 25))
        self.zoom_in.setObjectName("zoom_in")
        self.InputLabel = QtWidgets.QLabel(self.Main)
        self.InputLabel.setGeometry(QtCore.QRect(10, 10, 30, 20))
        self.InputLabel.setObjectName("InputLabel")
        self.OutputLabel = QtWidgets.QLabel(self.Main)
        self.OutputLabel.setGeometry(QtCore.QRect(10, 400, 40, 16))
        self.OutputLabel.setObjectName("OutputLabel")
        self.InputSpecLabel = QtWidgets.QLabel(self.Main)
        self.InputSpecLabel.setGeometry(QtCore.QRect(10, 201, 111, 21))
        self.InputSpecLabel.setObjectName("InputSpecLabel")
        self.OutputSpecLabel = QtWidgets.QLabel(self.Main)
        self.OutputSpecLabel.setGeometry(QtCore.QRect(10, 611, 121, 21))
        self.OutputSpecLabel.setObjectName("OutputSpecLabel")
        self.InputSignal = PlotWidget(self.Main)
        self.InputSignal.setGeometry(QtCore.QRect(7, 29, 891, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputSignal.sizePolicy().hasHeightForWidth())
        self.InputSignal.setSizePolicy(sizePolicy)
        self.InputSignal.setObjectName("InputSignal")
        self.OutputSpectro = PlotWidget(self.Main)
        self.OutputSpectro.setGeometry(QtCore.QRect(10, 631, 891, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutputSpectro.sizePolicy().hasHeightForWidth())
        self.OutputSpectro.setSizePolicy(sizePolicy)
        self.OutputSpectro.setObjectName("OutputSpectro")
        self.OutputSignal = PlotWidget(self.Main)
        self.OutputSignal.setGeometry(QtCore.QRect(10, 421, 891, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutputSignal.sizePolicy().hasHeightForWidth())
        self.OutputSignal.setSizePolicy(sizePolicy)
        self.OutputSignal.setObjectName("OutputSignal")
        self.InputSpectro = PlotWidget(self.Main)
        self.InputSpectro.setGeometry(QtCore.QRect(10, 221, 891, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputSpectro.sizePolicy().hasHeightForWidth())
        self.InputSpectro.setSizePolicy(sizePolicy)
        self.InputSpectro.setStyleSheet("")
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.InputSpectro.setBackgroundBrush(brush)
        self.InputSpectro.setObjectName("InputSpectro")
        self.widget = QtWidgets.QWidget(self.Main)
        self.widget.setGeometry(QtCore.QRect(940, 690, 411, 20))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Gain1Label = QtWidgets.QLabel(self.widget)
        self.Gain1Label.setObjectName("Gain1Label")
        self.horizontalLayout.addWidget(self.Gain1Label)
        self.Gain2Label = QtWidgets.QLabel(self.widget)
        self.Gain2Label.setObjectName("Gain2Label")
        self.horizontalLayout.addWidget(self.Gain2Label)
        self.Gain3Label = QtWidgets.QLabel(self.widget)
        self.Gain3Label.setObjectName("Gain3Label")
        self.horizontalLayout.addWidget(self.Gain3Label)
        self.Gain4Label = QtWidgets.QLabel(self.widget)
        self.Gain4Label.setObjectName("Gain4Label")
        self.horizontalLayout.addWidget(self.Gain4Label)
        self.Gain5Label = QtWidgets.QLabel(self.widget)
        self.Gain5Label.setObjectName("Gain5Label")
        self.horizontalLayout.addWidget(self.Gain5Label)
        self.Gain6Label = QtWidgets.QLabel(self.widget)
        self.Gain6Label.setObjectName("Gain6Label")
        self.horizontalLayout.addWidget(self.Gain6Label)
        self.Gain7Label = QtWidgets.QLabel(self.widget)
        self.Gain7Label.setObjectName("Gain7Label")
        self.horizontalLayout.addWidget(self.Gain7Label)
        self.Gain8Label = QtWidgets.QLabel(self.widget)
        self.Gain8Label.setObjectName("Gain8Label")
        self.horizontalLayout.addWidget(self.Gain8Label)
        self.Gain9Label = QtWidgets.QLabel(self.widget)
        self.Gain9Label.setObjectName("Gain9Label")
        self.horizontalLayout.addWidget(self.Gain9Label)
        self.Gain10Label = QtWidgets.QLabel(self.widget)
        self.Gain10Label.setObjectName("Gain10Label")
        self.horizontalLayout.addWidget(self.Gain10Label)
        self.GainMinLabel = QtWidgets.QLabel(self.widget)
        self.GainMinLabel.setObjectName("GainMinLabel")
        self.horizontalLayout.addWidget(self.GainMinLabel)
        self.GainMaxLabel = QtWidgets.QLabel(self.widget)
        self.GainMaxLabel.setObjectName("GainMaxLabel")
        self.horizontalLayout.addWidget(self.GainMaxLabel)
        self.widget1 = QtWidgets.QWidget(self.Main)
        self.widget1.setGeometry(QtCore.QRect(934, 670, 411, 17))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Slider1Label = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(6)
        font.setBold(False)
        font.setItalic(False)
        self.Slider1Label.setFont(font)
        self.Slider1Label.setStyleSheet("\n"
"font: 6pt \"MS Shell Dlg 2\";")
        self.Slider1Label.setObjectName("Slider1Label")
        self.horizontalLayout_2.addWidget(self.Slider1Label)
        self.Slider2Label = QtWidgets.QLabel(self.widget1)
        self.Slider2Label.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";")
        self.Slider2Label.setObjectName("Slider2Label")
        self.horizontalLayout_2.addWidget(self.Slider2Label)
        self.Slider3Label = QtWidgets.QLabel(self.widget1)
        self.Slider3Label.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.Slider3Label.setObjectName("Slider3Label")
        self.horizontalLayout_2.addWidget(self.Slider3Label)
        self.Slider4Label = QtWidgets.QLabel(self.widget1)
        self.Slider4Label.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";")
        self.Slider4Label.setObjectName("Slider4Label")
        self.horizontalLayout_2.addWidget(self.Slider4Label)
        self.Slider5Label = QtWidgets.QLabel(self.widget1)
        self.Slider5Label.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";")
        self.Slider5Label.setObjectName("Slider5Label")
        self.horizontalLayout_2.addWidget(self.Slider5Label)
        self.Slider6Label = QtWidgets.QLabel(self.widget1)
        self.Slider6Label.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";")
        self.Slider6Label.setObjectName("Slider6Label")
        self.horizontalLayout_2.addWidget(self.Slider6Label)
        self.Slider7Label = QtWidgets.QLabel(self.widget1)
        self.Slider7Label.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";")
        self.Slider7Label.setObjectName("Slider7Label")
        self.horizontalLayout_2.addWidget(self.Slider7Label)
        self.Slider8Label = QtWidgets.QLabel(self.widget1)
        self.Slider8Label.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";")
        self.Slider8Label.setObjectName("Slider8Label")
        self.horizontalLayout_2.addWidget(self.Slider8Label)
        self.Slider9Label = QtWidgets.QLabel(self.widget1)
        self.Slider9Label.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";")
        self.Slider9Label.setObjectName("Slider9Label")
        self.horizontalLayout_2.addWidget(self.Slider9Label)
        self.Slider10Label = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(6)
        font.setBold(False)
        font.setItalic(False)
        self.Slider10Label.setFont(font)
        self.Slider10Label.setStyleSheet("font: 6pt \"MS Shell Dlg 2\";")
        self.Slider10Label.setObjectName("Slider10Label")
        self.horizontalLayout_2.addWidget(self.Slider10Label)
        self.SliderMinLabel = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.SliderMinLabel.setFont(font)
        self.SliderMinLabel.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.SliderMinLabel.setObjectName("SliderMinLabel")
        self.horizontalLayout_2.addWidget(self.SliderMinLabel)
        self.SliderMaxLabel = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.SliderMaxLabel.setFont(font)
        self.SliderMaxLabel.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.SliderMaxLabel.setObjectName("SliderMaxLabel")
        self.horizontalLayout_2.addWidget(self.SliderMaxLabel)
        self.widget2 = QtWidgets.QWidget(self.Main)
        self.widget2.setGeometry(QtCore.QRect(934, 10, 411, 651))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Slider_1 = QtWidgets.QSlider(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_1.sizePolicy().hasHeightForWidth())
        self.Slider_1.setSizePolicy(sizePolicy)
        self.Slider_1.setMaximum(5)
        self.Slider_1.setSingleStep(1)
        self.Slider_1.setProperty("value", 0)
        self.Slider_1.setOrientation(QtCore.Qt.Vertical)
        self.Slider_1.setObjectName("Slider_1")
        self.horizontalLayout_3.addWidget(self.Slider_1)
        self.Slider_2 = QtWidgets.QSlider(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_2.sizePolicy().hasHeightForWidth())
        self.Slider_2.setSizePolicy(sizePolicy)
        self.Slider_2.setMaximum(5)
        self.Slider_2.setSliderPosition(0)
        self.Slider_2.setOrientation(QtCore.Qt.Vertical)
        self.Slider_2.setObjectName("Slider_2")
        self.horizontalLayout_3.addWidget(self.Slider_2)
        self.Slider_3 = QtWidgets.QSlider(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_3.sizePolicy().hasHeightForWidth())
        self.Slider_3.setSizePolicy(sizePolicy)
        self.Slider_3.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 86, 158, 255), stop:1 rgba(255, 255, 255, 255));")
        self.Slider_3.setMaximum(5)
        self.Slider_3.setOrientation(QtCore.Qt.Vertical)
        self.Slider_3.setObjectName("Slider_3")
        self.horizontalLayout_3.addWidget(self.Slider_3)
        self.Slider_4 = QtWidgets.QSlider(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_4.sizePolicy().hasHeightForWidth())
        self.Slider_4.setSizePolicy(sizePolicy)
        self.Slider_4.setMaximum(5)
        self.Slider_4.setOrientation(QtCore.Qt.Vertical)
        self.Slider_4.setObjectName("Slider_4")
        self.horizontalLayout_3.addWidget(self.Slider_4)
        self.Slider_5 = QtWidgets.QSlider(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_5.sizePolicy().hasHeightForWidth())
        self.Slider_5.setSizePolicy(sizePolicy)
        self.Slider_5.setMaximum(5)
        self.Slider_5.setOrientation(QtCore.Qt.Vertical)
        self.Slider_5.setObjectName("Slider_5")
        self.horizontalLayout_3.addWidget(self.Slider_5)
        self.Slider_6 = QtWidgets.QSlider(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_6.sizePolicy().hasHeightForWidth())
        self.Slider_6.setSizePolicy(sizePolicy)
        self.Slider_6.setMaximum(5)
        self.Slider_6.setOrientation(QtCore.Qt.Vertical)
        self.Slider_6.setObjectName("Slider_6")
        self.horizontalLayout_3.addWidget(self.Slider_6)
        self.Slider_7 = QtWidgets.QSlider(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_7.sizePolicy().hasHeightForWidth())
        self.Slider_7.setSizePolicy(sizePolicy)
        self.Slider_7.setMaximum(5)
        self.Slider_7.setOrientation(QtCore.Qt.Vertical)
        self.Slider_7.setObjectName("Slider_7")
        self.horizontalLayout_3.addWidget(self.Slider_7)
        self.Slider_8 = QtWidgets.QSlider(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_8.sizePolicy().hasHeightForWidth())
        self.Slider_8.setSizePolicy(sizePolicy)
        self.Slider_8.setMaximum(5)
        self.Slider_8.setOrientation(QtCore.Qt.Vertical)
        self.Slider_8.setObjectName("Slider_8")
        self.horizontalLayout_3.addWidget(self.Slider_8)
        self.Slider_9 = QtWidgets.QSlider(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_9.sizePolicy().hasHeightForWidth())
        self.Slider_9.setSizePolicy(sizePolicy)
        self.Slider_9.setMaximum(5)
        self.Slider_9.setOrientation(QtCore.Qt.Vertical)
        self.Slider_9.setObjectName("Slider_9")
        self.horizontalLayout_3.addWidget(self.Slider_9)
        self.Slider_10 = QtWidgets.QSlider(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_10.sizePolicy().hasHeightForWidth())
        self.Slider_10.setSizePolicy(sizePolicy)
        self.Slider_10.setMaximum(5)
        self.Slider_10.setOrientation(QtCore.Qt.Vertical)
        self.Slider_10.setObjectName("Slider_10")
        self.horizontalLayout_3.addWidget(self.Slider_10)
        self.Slider_11 = QtWidgets.QSlider(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_11.sizePolicy().hasHeightForWidth())
        self.Slider_11.setSizePolicy(sizePolicy)
        self.Slider_11.setMaximum(5)
        self.Slider_11.setOrientation(QtCore.Qt.Vertical)
        self.Slider_11.setObjectName("Slider_11")
        self.horizontalLayout_3.addWidget(self.Slider_11)
        self.Slider_12 = QtWidgets.QSlider(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_12.sizePolicy().hasHeightForWidth())
        self.Slider_12.setSizePolicy(sizePolicy)
        self.Slider_12.setMaximum(5)
        self.Slider_12.setOrientation(QtCore.Qt.Vertical)
        self.Slider_12.setObjectName("Slider_12")
        self.horizontalLayout_3.addWidget(self.Slider_12)
        self.widget3 = QtWidgets.QWidget(self.Main)
        self.widget3.setGeometry(QtCore.QRect(1004, 720, 261, 32))
        self.widget3.setObjectName("widget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Play_Button = QtWidgets.QPushButton(self.widget3)
        self.Play_Button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Play_Button.sizePolicy().hasHeightForWidth())
        self.Play_Button.setSizePolicy(sizePolicy)
        self.Play_Button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 86, 158, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"font: 63 14pt \"Yu Gothic UI Semibold\";\n"
"border: 2px solid #555;\n"
"border-radius: 30px;")
        self.Play_Button.setObjectName("Play_Button")
        self.horizontalLayout_4.addWidget(self.Play_Button)
        self.Stop_Button = QtWidgets.QPushButton(self.widget3)
        self.Stop_Button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Stop_Button.sizePolicy().hasHeightForWidth())
        self.Stop_Button.setSizePolicy(sizePolicy)
        self.Stop_Button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 86, 158, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"font: 63 14pt \"Yu Gothic UI Semibold\";\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"")
        self.Stop_Button.setFlat(False)
        self.Stop_Button.setObjectName("Stop_Button")
        self.horizontalLayout_4.addWidget(self.Stop_Button)
        self.Stop_Button.raise_()
        self.Play_Button.raise_()
        self.InputLabel.raise_()
        self.OutputLabel.raise_()
        self.InputSpecLabel.raise_()
        self.OutputSpecLabel.raise_()
        self.InputSignal.raise_()
        self.OutputSpectro.raise_()
        self.OutputSignal.raise_()
        self.InputSpectro.raise_()
        self.Slider_1.raise_()
        self.Slider_3.raise_()
        self.Slider_2.raise_()
        self.Slider_5.raise_()
        self.Slider_7.raise_()
        self.Slider_6.raise_()
        self.Slider_4.raise_()
        self.Slider_9.raise_()
        self.Slider_10.raise_()
        self.Slider_8.raise_()
        self.Slider_11.raise_()
        self.Slider_12.raise_()
        self.GainMinLabel.raise_()
        self.GainMaxLabel.raise_()
        self.Gain1Label.raise_()
        self.Gain3Label.raise_()
        self.Gain4Label.raise_()
        self.Gain2Label.raise_()
        self.Gain7Label.raise_()
        self.Gain6Label.raise_()
        self.Gain5Label.raise_()
        self.Gain10Label.raise_()
        self.Gain9Label.raise_()
        self.Gain8Label.raise_()
        self.Slider6Label.raise_()
        self.Slider8Label.raise_()
        self.Slider5Label.raise_()
        self.Slider9Label.raise_()
        self.SliderMinLabel.raise_()
        self.Slider3Label.raise_()
        self.Slider1Label.raise_()
        self.SliderMaxLabel.raise_()
        self.Slider7Label.raise_()
        self.Slider10Label.raise_()
        self.Slider4Label.raise_()
        self.Slider2Label.raise_()
        self.groupBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1390, 22))
        self.menubar.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(74, 74, 74);")
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setMouseTracking(True)
        self.menufile.setTabletTracking(False)
        self.menufile.setFocusPolicy(QtCore.Qt.NoFocus)
        self.menufile.setAutoFillBackground(False)
        self.menufile.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(80, 80, 80);")
        self.menufile.setObjectName("menufile")
        self.menuColor_Palette = QtWidgets.QMenu(self.menubar)
        self.menuColor_Palette.setObjectName("menuColor_Palette")
        self.menuChannels = QtWidgets.QMenu(self.menubar)
        self.menuChannels.setObjectName("menuChannels")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_new_win = QtWidgets.QAction(MainWindow)
        self.action_new_win.setObjectName("action_new_win")
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_clear = QtWidgets.QAction(MainWindow)
        self.action_clear.setObjectName("action_clear")
        self.actionPalette_2 = QtWidgets.QAction(MainWindow)
        self.actionPalette_2.setObjectName("actionPalette_2")
        self.actionPalette_1 = QtWidgets.QAction(MainWindow)
        self.actionPalette_1.setObjectName("actionPalette_1")
        self.actionPalette_3 = QtWidgets.QAction(MainWindow)
        self.actionPalette_3.setObjectName("actionPalette_3")
        self.actionPalette_4 = QtWidgets.QAction(MainWindow)
        self.actionPalette_4.setObjectName("actionPalette_4")
        self.actionPalette_5 = QtWidgets.QAction(MainWindow)
        self.actionPalette_5.setObjectName("actionPalette_5")
        self.actionSave_as_PDF = QtWidgets.QAction(MainWindow)
        self.actionSave_as_PDF.setObjectName("actionSave_as_PDF")
        self.Channel1 = QtWidgets.QAction(MainWindow)
        self.Channel1.setCheckable(True)
        self.Channel1.setObjectName("Channel1")
        self.Channel2 = QtWidgets.QAction(MainWindow)
        self.Channel2.setCheckable(True)
        self.Channel2.setObjectName("Channel2")
        self.menufile.addAction(self.action_new_win)
        self.menufile.addAction(self.action_open)
        self.menufile.addAction(self.action_save)
        self.menufile.addAction(self.action_clear)
        self.menufile.addAction(self.actionSave_as_PDF)
        self.menuColor_Palette.addAction(self.actionPalette_1)
        self.menuColor_Palette.addAction(self.actionPalette_2)
        self.menuColor_Palette.addAction(self.actionPalette_3)
        self.menuColor_Palette.addAction(self.actionPalette_4)
        self.menuColor_Palette.addAction(self.actionPalette_5)
        self.menuChannels.addAction(self.Channel1)
        self.menuChannels.addAction(self.Channel2)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuColor_Palette.menuAction())
        self.menubar.addAction(self.menuChannels.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Equalizer"))
        self.right_button.setShortcut(_translate("MainWindow", "Right"))
        self.left_button.setShortcut(_translate("MainWindow", "Left"))
        self.up_button.setShortcut(_translate("MainWindow", "Up"))
        self.down_button.setShortcut(_translate("MainWindow", "Down"))
        self.zoom_out.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.zoom_in.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.InputLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Input <br/></span></p></body></html>"))
        self.OutputLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Output</span></p></body></html>"))
        self.InputSpecLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Input Spectrogram</span></p></body></html>"))
        self.OutputSpecLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Output Spectrogram</span></p></body></html>"))
        self.Gain1Label.setText(_translate("MainWindow", "0"))
        self.Gain2Label.setText(_translate("MainWindow", "0"))
        self.Gain3Label.setText(_translate("MainWindow", "0"))
        self.Gain4Label.setText(_translate("MainWindow", "0"))
        self.Gain5Label.setText(_translate("MainWindow", "0"))
        self.Gain6Label.setText(_translate("MainWindow", "0"))
        self.Gain7Label.setText(_translate("MainWindow", "0"))
        self.Gain8Label.setText(_translate("MainWindow", "0"))
        self.Gain9Label.setText(_translate("MainWindow", "0"))
        self.Gain10Label.setText(_translate("MainWindow", "0"))
        self.GainMinLabel.setText(_translate("MainWindow", "0"))
        self.GainMaxLabel.setText(_translate("MainWindow", "0"))
        self.Slider1Label.setText(_translate("MainWindow", "60 Hz"))
        self.Slider2Label.setText(_translate("MainWindow", "170 Hz"))
        self.Slider3Label.setText(_translate("MainWindow", "310 Hz"))
        self.Slider4Label.setText(_translate("MainWindow", "600 Hz"))
        self.Slider5Label.setText(_translate("MainWindow", "1 K Hz"))
        self.Slider6Label.setText(_translate("MainWindow", "3 KHz"))
        self.Slider7Label.setText(_translate("MainWindow", "6 KHz"))
        self.Slider8Label.setText(_translate("MainWindow", "12 KHz"))
        self.Slider9Label.setText(_translate("MainWindow", "14 KHz"))
        self.Slider10Label.setText(_translate("MainWindow", "16 KHz"))
        self.SliderMinLabel.setText(_translate("MainWindow", "min"))
        self.SliderMaxLabel.setText(_translate("MainWindow", "max"))
        self.Play_Button.setText(_translate("MainWindow", "Play"))
        self.Play_Button.setShortcut(_translate("MainWindow", "Alt+P"))
        self.Stop_Button.setText(_translate("MainWindow", "Stop"))
        self.Stop_Button.setShortcut(_translate("MainWindow", "Alt+S"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.menuColor_Palette.setTitle(_translate("MainWindow", "Color Palette"))
        self.menuChannels.setTitle(_translate("MainWindow", "Channels"))
        self.action_new_win.setText(_translate("MainWindow", "New Window"))
        self.action_new_win.setToolTip(_translate("MainWindow", "New Window"))
        self.action_new_win.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_open.setText(_translate("MainWindow", "Open"))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_save.setText(_translate("MainWindow", "Save"))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_clear.setText(_translate("MainWindow", "Clear"))
        self.action_clear.setToolTip(_translate("MainWindow", "Clear"))
        self.action_clear.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPalette_2.setText(_translate("MainWindow", "Palette 2"))
        self.actionPalette_2.setShortcut(_translate("MainWindow", "Alt+2"))
        self.actionPalette_1.setText(_translate("MainWindow", "Palette 1"))
        self.actionPalette_1.setShortcut(_translate("MainWindow", "Alt+1"))
        self.actionPalette_3.setText(_translate("MainWindow", "Palette 3"))
        self.actionPalette_3.setShortcut(_translate("MainWindow", "Alt+3"))
        self.actionPalette_4.setText(_translate("MainWindow", "Palette 4 "))
        self.actionPalette_4.setShortcut(_translate("MainWindow", "Alt+4"))
        self.actionPalette_5.setText(_translate("MainWindow", "Palette 5"))
        self.actionPalette_5.setShortcut(_translate("MainWindow", "Alt+5"))
        self.actionSave_as_PDF.setText(_translate("MainWindow", "Save as PDF"))
        self.actionSave_as_PDF.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.Channel1.setText(_translate("MainWindow", "Channel 1"))
        self.Channel2.setText(_translate("MainWindow", "Channel 2"))

from pyqtgraph import PlotWidget
import img_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

