# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AudioEqualizer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1420, 899)
        MainWindow.setMouseTracking(True)
        MainWindow.setAccessibleName("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(12, 12, 12);\n"
"color: rgb(255, 255, 255);\n"
"")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Main = QtWidgets.QGroupBox(self.centralwidget)
        self.Main.setEnabled(True)
        self.Main.setGeometry(QtCore.QRect(10, 10, 1401, 821))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.Main.sizePolicy().hasHeightForWidth())
        self.Main.setSizePolicy(sizePolicy)
        self.Main.setMinimumSize(QtCore.QSize(1344, 759))
        self.Main.setBaseSize(QtCore.QSize(0, 0))
        self.Main.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Main.setObjectName("Main")
        self.layoutWidget = QtWidgets.QWidget(self.Main)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 780, 821, 20))
        self.layoutWidget.setObjectName("layoutWidget")
        self.numberslayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.numberslayout.setContentsMargins(0, 0, 0, 0)
        self.numberslayout.setObjectName("numberslayout")
        self.Gain1Label = QtWidgets.QLabel(self.layoutWidget)
        self.Gain1Label.setObjectName("Gain1Label")
        self.numberslayout.addWidget(self.Gain1Label)
        self.Gain2Label = QtWidgets.QLabel(self.layoutWidget)
        self.Gain2Label.setObjectName("Gain2Label")
        self.numberslayout.addWidget(self.Gain2Label)
        self.Gain3Label = QtWidgets.QLabel(self.layoutWidget)
        self.Gain3Label.setObjectName("Gain3Label")
        self.numberslayout.addWidget(self.Gain3Label)
        self.Gain4Label = QtWidgets.QLabel(self.layoutWidget)
        self.Gain4Label.setObjectName("Gain4Label")
        self.numberslayout.addWidget(self.Gain4Label)
        self.Gain5Label = QtWidgets.QLabel(self.layoutWidget)
        self.Gain5Label.setObjectName("Gain5Label")
        self.numberslayout.addWidget(self.Gain5Label)
        self.Gain6Label = QtWidgets.QLabel(self.layoutWidget)
        self.Gain6Label.setObjectName("Gain6Label")
        self.numberslayout.addWidget(self.Gain6Label)
        self.Gain7Label = QtWidgets.QLabel(self.layoutWidget)
        self.Gain7Label.setObjectName("Gain7Label")
        self.numberslayout.addWidget(self.Gain7Label)
        self.Gain8Label = QtWidgets.QLabel(self.layoutWidget)
        self.Gain8Label.setObjectName("Gain8Label")
        self.numberslayout.addWidget(self.Gain8Label)
        self.Gain9Label = QtWidgets.QLabel(self.layoutWidget)
        self.Gain9Label.setObjectName("Gain9Label")
        self.numberslayout.addWidget(self.Gain9Label)
        self.Gain10Label = QtWidgets.QLabel(self.layoutWidget)
        self.Gain10Label.setObjectName("Gain10Label")
        self.numberslayout.addWidget(self.Gain10Label)
        self.layoutWidget1 = QtWidgets.QWidget(self.Main)
        self.layoutWidget1.setGeometry(QtCore.QRect(930, 660, 51, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.labelslayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.labelslayout.setContentsMargins(0, 0, 0, 0)
        self.labelslayout.setObjectName("labelslayout")
        self.SliderMaxLabel = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        self.SliderMaxLabel.setFont(font)
        self.SliderMaxLabel.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.SliderMaxLabel.setObjectName("SliderMaxLabel")
        self.labelslayout.addWidget(self.SliderMaxLabel)
        self.GainMaxLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.GainMaxLabel.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.GainMaxLabel.setObjectName("GainMaxLabel")
        self.labelslayout.addWidget(self.GainMaxLabel)
        self.layoutWidget2 = QtWidgets.QWidget(self.Main)
        self.layoutWidget2.setGeometry(QtCore.QRect(70, 620, 821, 151))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.sliderslayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.sliderslayout.setContentsMargins(0, 0, 0, 0)
        self.sliderslayout.setObjectName("sliderslayout")
        self.Slider_1 = QtWidgets.QSlider(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_1.sizePolicy().hasHeightForWidth())
        self.Slider_1.setSizePolicy(sizePolicy)
        self.Slider_1.setMaximum(5)
        self.Slider_1.setSingleStep(1)
        self.Slider_1.setProperty("value", 1)
        self.Slider_1.setOrientation(QtCore.Qt.Vertical)
        self.Slider_1.setObjectName("Slider_1")
        self.sliderslayout.addWidget(self.Slider_1)
        self.Slider_2 = QtWidgets.QSlider(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_2.sizePolicy().hasHeightForWidth())
        self.Slider_2.setSizePolicy(sizePolicy)
        self.Slider_2.setMaximum(5)
        self.Slider_2.setProperty("value", 1)
        self.Slider_2.setSliderPosition(1)
        self.Slider_2.setOrientation(QtCore.Qt.Vertical)
        self.Slider_2.setObjectName("Slider_2")
        self.sliderslayout.addWidget(self.Slider_2)
        self.Slider_3 = QtWidgets.QSlider(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_3.sizePolicy().hasHeightForWidth())
        self.Slider_3.setSizePolicy(sizePolicy)
        self.Slider_3.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 86, 158, 255), stop:1 rgba(255, 255, 255, 255));")
        self.Slider_3.setMaximum(5)
        self.Slider_3.setProperty("value", 1)
        self.Slider_3.setOrientation(QtCore.Qt.Vertical)
        self.Slider_3.setObjectName("Slider_3")
        self.sliderslayout.addWidget(self.Slider_3)
        self.Slider_4 = QtWidgets.QSlider(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_4.sizePolicy().hasHeightForWidth())
        self.Slider_4.setSizePolicy(sizePolicy)
        self.Slider_4.setMaximum(5)
        self.Slider_4.setProperty("value", 1)
        self.Slider_4.setOrientation(QtCore.Qt.Vertical)
        self.Slider_4.setObjectName("Slider_4")
        self.sliderslayout.addWidget(self.Slider_4)
        self.Slider_5 = QtWidgets.QSlider(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_5.sizePolicy().hasHeightForWidth())
        self.Slider_5.setSizePolicy(sizePolicy)
        self.Slider_5.setMaximum(5)
        self.Slider_5.setProperty("value", 1)
        self.Slider_5.setOrientation(QtCore.Qt.Vertical)
        self.Slider_5.setObjectName("Slider_5")
        self.sliderslayout.addWidget(self.Slider_5)
        self.Slider_6 = QtWidgets.QSlider(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_6.sizePolicy().hasHeightForWidth())
        self.Slider_6.setSizePolicy(sizePolicy)
        self.Slider_6.setMaximum(5)
        self.Slider_6.setProperty("value", 1)
        self.Slider_6.setOrientation(QtCore.Qt.Vertical)
        self.Slider_6.setObjectName("Slider_6")
        self.sliderslayout.addWidget(self.Slider_6)
        self.Slider_7 = QtWidgets.QSlider(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_7.sizePolicy().hasHeightForWidth())
        self.Slider_7.setSizePolicy(sizePolicy)
        self.Slider_7.setMaximum(5)
        self.Slider_7.setProperty("value", 1)
        self.Slider_7.setOrientation(QtCore.Qt.Vertical)
        self.Slider_7.setObjectName("Slider_7")
        self.sliderslayout.addWidget(self.Slider_7)
        self.Slider_8 = QtWidgets.QSlider(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_8.sizePolicy().hasHeightForWidth())
        self.Slider_8.setSizePolicy(sizePolicy)
        self.Slider_8.setMaximum(5)
        self.Slider_8.setProperty("value", 1)
        self.Slider_8.setOrientation(QtCore.Qt.Vertical)
        self.Slider_8.setObjectName("Slider_8")
        self.sliderslayout.addWidget(self.Slider_8)
        self.Slider_9 = QtWidgets.QSlider(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_9.sizePolicy().hasHeightForWidth())
        self.Slider_9.setSizePolicy(sizePolicy)
        self.Slider_9.setMaximum(5)
        self.Slider_9.setProperty("value", 1)
        self.Slider_9.setOrientation(QtCore.Qt.Vertical)
        self.Slider_9.setObjectName("Slider_9")
        self.sliderslayout.addWidget(self.Slider_9)
        self.Slider_10 = QtWidgets.QSlider(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Slider_10.sizePolicy().hasHeightForWidth())
        self.Slider_10.setSizePolicy(sizePolicy)
        self.Slider_10.setMaximum(5)
        self.Slider_10.setProperty("value", 1)
        self.Slider_10.setOrientation(QtCore.Qt.Vertical)
        self.Slider_10.setObjectName("Slider_10")
        self.sliderslayout.addWidget(self.Slider_10)
        self.layoutWidget3 = QtWidgets.QWidget(self.Main)
        self.layoutWidget3.setGeometry(QtCore.QRect(1000, 710, 351, 37))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.buttonslayout = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.buttonslayout.setContentsMargins(0, 0, 0, 0)
        self.buttonslayout.setObjectName("buttonslayout")
        self.OutputSpectro = PlotWidget(self.Main)
        self.OutputSpectro.setGeometry(QtCore.QRect(930, 40, 451, 561))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutputSpectro.sizePolicy().hasHeightForWidth())
        self.OutputSpectro.setSizePolicy(sizePolicy)
        self.OutputSpectro.setObjectName("OutputSpectro")
        self.OutputSpecLabel = QtWidgets.QLabel(self.Main)
        self.OutputSpecLabel.setGeometry(QtCore.QRect(930, 10, 441, 21))
        self.OutputSpecLabel.setObjectName("OutputSpecLabel")
        self.layoutWidget_3 = QtWidgets.QWidget(self.Main)
        self.layoutWidget_3.setGeometry(QtCore.QRect(1000, 750, 351, 41))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.sliderslayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.sliderslayout_3.setContentsMargins(0, 0, 0, 0)
        self.sliderslayout_3.setObjectName("sliderslayout_3")
        self.zoom_in = QtWidgets.QPushButton(self.layoutWidget_3)
        self.zoom_in.setStyleSheet("QPushButton { background-color: white; }")
        self.zoom_in.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/zoomin.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_in.setIcon(icon)
        self.zoom_in.setIconSize(QtCore.QSize(25, 25))
        self.zoom_in.setObjectName("zoom_in")
        self.sliderslayout_3.addWidget(self.zoom_in)
        self.zoom_out = QtWidgets.QPushButton(self.layoutWidget_3)
        self.zoom_out.setStyleSheet("QPushButton { background-color: white; }")
        self.zoom_out.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/zoomout.JPG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_out.setIcon(icon1)
        self.zoom_out.setIconSize(QtCore.QSize(25, 25))
        self.zoom_out.setObjectName("zoom_out")
        self.sliderslayout_3.addWidget(self.zoom_out)
        self.up_button = QtWidgets.QPushButton(self.layoutWidget_3)
        self.up_button.setStyleSheet("QPushButton { background-color: white; }")
        self.up_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/uparrw-Copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.up_button.setIcon(icon2)
        self.up_button.setIconSize(QtCore.QSize(25, 25))
        self.up_button.setObjectName("up_button")
        self.sliderslayout_3.addWidget(self.up_button)
        self.down_button = QtWidgets.QPushButton(self.layoutWidget_3)
        self.down_button.setStyleSheet("QPushButton { background-color: white; }")
        self.down_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/dwnarrw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.down_button.setIcon(icon3)
        self.down_button.setIconSize(QtCore.QSize(25, 25))
        self.down_button.setObjectName("down_button")
        self.sliderslayout_3.addWidget(self.down_button)
        self.left_button = QtWidgets.QPushButton(self.layoutWidget_3)
        self.left_button.setStyleSheet("QPushButton { background-color: white; }")
        self.left_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/larrw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.left_button.setIcon(icon4)
        self.left_button.setIconSize(QtCore.QSize(25, 25))
        self.left_button.setObjectName("left_button")
        self.sliderslayout_3.addWidget(self.left_button)
        self.right_button = QtWidgets.QPushButton(self.layoutWidget_3)
        self.right_button.setStyleSheet("QPushButton { background-color: white; }")
        self.right_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/Rarrw.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.right_button.setIcon(icon5)
        self.right_button.setIconSize(QtCore.QSize(25, 25))
        self.right_button.setObjectName("right_button")
        self.sliderslayout_3.addWidget(self.right_button)
        self.Slider_11 = QtWidgets.QSlider(self.Main)
        self.Slider_11.setGeometry(QtCore.QRect(979, 620, 391, 22))
        self.Slider_11.setMaximum(100)
        self.Slider_11.setProperty("value", 50)
        self.Slider_11.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_11.setObjectName("Slider_11")
        self.Slider_12 = QtWidgets.QSlider(self.Main)
        self.Slider_12.setGeometry(QtCore.QRect(979, 660, 391, 22))
        self.Slider_12.setMinimum(0)
        self.Slider_12.setMaximum(100)
        self.Slider_12.setProperty("value", 100)
        self.Slider_12.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_12.setObjectName("Slider_12")
        self.layoutWidget_2 = QtWidgets.QWidget(self.Main)
        self.layoutWidget_2.setGeometry(QtCore.QRect(930, 620, 44, 23))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.labelslayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.labelslayout_2.setContentsMargins(0, 0, 0, 0)
        self.labelslayout_2.setObjectName("labelslayout_2")
        self.SliderMinLabel = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        self.SliderMinLabel.setFont(font)
        self.SliderMinLabel.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.SliderMinLabel.setObjectName("SliderMinLabel")
        self.labelslayout_2.addWidget(self.SliderMinLabel)
        self.GainMinLabel = QtWidgets.QLabel(self.layoutWidget_2)
        self.GainMinLabel.setObjectName("GainMinLabel")
        self.labelslayout_2.addWidget(self.GainMinLabel)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Main)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 40, 871, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.InputSignal = PlotWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputSignal.sizePolicy().hasHeightForWidth())
        self.InputSignal.setSizePolicy(sizePolicy)
        self.InputSignal.setObjectName("InputSignal")
        self.verticalLayout.addWidget(self.InputSignal)
        self.InputSpectro = PlotWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputSpectro.sizePolicy().hasHeightForWidth())
        self.InputSpectro.setSizePolicy(sizePolicy)
        self.InputSpectro.setObjectName("InputSpectro")
        self.verticalLayout.addWidget(self.InputSpectro)
        self.OutputSignal = PlotWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OutputSignal.sizePolicy().hasHeightForWidth())
        self.OutputSignal.setSizePolicy(sizePolicy)
        self.OutputSignal.setStyleSheet("")
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.OutputSignal.setBackgroundBrush(brush)
        self.OutputSignal.setObjectName("OutputSignal")
        self.verticalLayout.addWidget(self.OutputSignal)
        self.show_ISpectroCh = QtWidgets.QCheckBox(self.Main)
        self.show_ISpectroCh.setGeometry(QtCore.QRect(50, 10, 201, 20))
        self.show_ISpectroCh.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.show_ISpectroCh.setObjectName("show_ISpectroCh")
        self.Stop_Button = QtWidgets.QPushButton(self.Main)
        self.Stop_Button.setEnabled(True)
        self.Stop_Button.setGeometry(QtCore.QRect(1179, 711, 171, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Stop_Button.sizePolicy().hasHeightForWidth())
        self.Stop_Button.setSizePolicy(sizePolicy)
        self.Stop_Button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 86, 158, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"font: 63 14pt \"Yu Gothic UI Semibold\";\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"")
        self.Stop_Button.setFlat(False)
        self.Stop_Button.setObjectName("Stop_Button")
        self.Play_Button = QtWidgets.QPushButton(self.Main)
        self.Play_Button.setEnabled(True)
        self.Play_Button.setGeometry(QtCore.QRect(1001, 711, 171, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Play_Button.sizePolicy().hasHeightForWidth())
        self.Play_Button.setSizePolicy(sizePolicy)
        self.Play_Button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 86, 158, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);\n"
"font: 63 14pt \"Yu Gothic UI Semibold\";\n"
"border: 2px solid #555;\n"
"border-radius: 30px;")
        self.Play_Button.setObjectName("Play_Button")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.Main)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 34, 641))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/img/input_img.JPG"))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/img/output_img.JPG"))
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1420, 22))
        self.menubar.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(74, 74, 74);")
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setMouseTracking(True)
        self.menufile.setTabletTracking(False)
        self.menufile.setFocusPolicy(QtCore.Qt.NoFocus)
        self.menufile.setAutoFillBackground(False)
        self.menufile.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(80, 80, 80);")
        self.menufile.setObjectName("menufile")
        self.menuColor_Palette = QtWidgets.QMenu(self.menubar)
        self.menuColor_Palette.setStyleSheet("background-color: rgb(80, 80, 80);")
        self.menuColor_Palette.setObjectName("menuColor_Palette")
        self.menuChannels = QtWidgets.QMenu(self.menubar)
        self.menuChannels.setStyleSheet("background-color: rgb(80, 80, 80);")
        self.menuChannels.setObjectName("menuChannels")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_new_win = QtWidgets.QAction(MainWindow)
        self.action_new_win.setObjectName("action_new_win")
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_clear = QtWidgets.QAction(MainWindow)
        self.action_clear.setObjectName("action_clear")
        self.actionPalette_2 = QtWidgets.QAction(MainWindow)
        self.actionPalette_2.setObjectName("actionPalette_2")
        self.actionPalette_1 = QtWidgets.QAction(MainWindow)
        self.actionPalette_1.setObjectName("actionPalette_1")
        self.actionPalette_3 = QtWidgets.QAction(MainWindow)
        self.actionPalette_3.setObjectName("actionPalette_3")
        self.actionPalette_4 = QtWidgets.QAction(MainWindow)
        self.actionPalette_4.setObjectName("actionPalette_4")
        self.actionPalette_5 = QtWidgets.QAction(MainWindow)
        self.actionPalette_5.setObjectName("actionPalette_5")
        self.actionSave_as_PDF = QtWidgets.QAction(MainWindow)
        self.actionSave_as_PDF.setObjectName("actionSave_as_PDF")
        self.InputCh = QtWidgets.QAction(MainWindow)
        self.InputCh.setCheckable(True)
        self.InputCh.setObjectName("InputCh")
        self.ISpectroCh = QtWidgets.QAction(MainWindow)
        self.ISpectroCh.setCheckable(True)
        self.ISpectroCh.setObjectName("ISpectroCh")
        self.OutputCh = QtWidgets.QAction(MainWindow)
        self.OutputCh.setCheckable(True)
        self.OutputCh.setObjectName("OutputCh")
        self.OSpectroCh = QtWidgets.QAction(MainWindow)
        self.OSpectroCh.setCheckable(True)
        self.OSpectroCh.setObjectName("OSpectroCh")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actiontemp = QtWidgets.QAction(MainWindow)
        self.actiontemp.setObjectName("actiontemp")
        self.menufile.addAction(self.action_new_win)
        self.menufile.addAction(self.action_open)
        self.menufile.addAction(self.action_clear)
        self.menufile.addAction(self.actionSave_as_PDF)
        self.menufile.addAction(self.actionClose)
        self.menuColor_Palette.addAction(self.actionPalette_1)
        self.menuColor_Palette.addAction(self.actionPalette_2)
        self.menuColor_Palette.addAction(self.actionPalette_3)
        self.menuColor_Palette.addAction(self.actionPalette_4)
        self.menuColor_Palette.addAction(self.actionPalette_5)
        self.menuChannels.addAction(self.InputCh)
        self.menuChannels.addAction(self.ISpectroCh)
        self.menuChannels.addAction(self.OutputCh)
        self.menuChannels.addAction(self.OSpectroCh)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuColor_Palette.menuAction())
        self.menubar.addAction(self.menuChannels.menuAction())

        self.retranslateUi(MainWindow)
        self.Slider_2.valueChanged['int'].connect(self.Gain2Label.setNum)
        self.Slider_3.valueChanged['int'].connect(self.Gain3Label.setNum)
        self.Slider_6.valueChanged['int'].connect(self.Gain6Label.setNum)
        self.Slider_9.valueChanged['int'].connect(self.Gain9Label.setNum)
        self.Slider_10.valueChanged['int'].connect(self.Gain10Label.setNum)
        self.show_ISpectroCh.stateChanged['int'].connect(self.InputSpectro.show)
        self.Slider_7.valueChanged['int'].connect(self.Gain7Label.setNum)
        self.Slider_5.valueChanged['int'].connect(self.Gain5Label.setNum)
        self.Slider_8.valueChanged['int'].connect(self.Gain8Label.setNum)
        self.Slider_12.valueChanged['int'].connect(self.GainMaxLabel.setNum)
        self.Slider_4.valueChanged['int'].connect(self.Gain4Label.setNum)
        self.Slider_11.valueChanged['int'].connect(self.GainMinLabel.setNum)
        self.show_ISpectroCh.stateChanged['int'].connect(self.InputSpectro.hide)
        self.Slider_1.valueChanged['int'].connect(self.Gain1Label.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Equalizer"))
        self.Gain1Label.setText(_translate("MainWindow", "1"))
        self.Gain2Label.setText(_translate("MainWindow", "1"))
        self.Gain3Label.setText(_translate("MainWindow", "1"))
        self.Gain4Label.setText(_translate("MainWindow", "1"))
        self.Gain5Label.setText(_translate("MainWindow", "1"))
        self.Gain6Label.setText(_translate("MainWindow", "1"))
        self.Gain7Label.setText(_translate("MainWindow", "1"))
        self.Gain8Label.setText(_translate("MainWindow", "1"))
        self.Gain9Label.setText(_translate("MainWindow", "1"))
        self.Gain10Label.setText(_translate("MainWindow", "1"))
        self.SliderMaxLabel.setText(_translate("MainWindow", "Max"))
        self.GainMaxLabel.setText(_translate("MainWindow", "100"))
        self.OutputSpecLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Output Spectrogram</span></p></body></html>"))
        self.zoom_in.setShortcut(_translate("MainWindow", "Ctrl+="))
        self.zoom_out.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.up_button.setShortcut(_translate("MainWindow", "Up"))
        self.down_button.setShortcut(_translate("MainWindow", "Down"))
        self.left_button.setShortcut(_translate("MainWindow", "Left"))
        self.right_button.setShortcut(_translate("MainWindow", "Right"))
        self.SliderMinLabel.setText(_translate("MainWindow", "Min  "))
        self.GainMinLabel.setText(_translate("MainWindow", "50"))
        self.show_ISpectroCh.setText(_translate("MainWindow", "Hide spectrogram"))
        self.show_ISpectroCh.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.Stop_Button.setText(_translate("MainWindow", "Stop"))
        self.Stop_Button.setShortcut(_translate("MainWindow", "Alt+S"))
        self.Play_Button.setText(_translate("MainWindow", "Play"))
        self.Play_Button.setShortcut(_translate("MainWindow", "Alt+P"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.menuColor_Palette.setTitle(_translate("MainWindow", "Color Palette"))
        self.menuChannels.setTitle(_translate("MainWindow", "Channels"))
        self.action_new_win.setText(_translate("MainWindow", "New Window"))
        self.action_new_win.setToolTip(_translate("MainWindow", "New Window"))
        self.action_new_win.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_open.setText(_translate("MainWindow", "Open"))
        self.action_open.setShortcut(_translate("MainWindow", "Alt+O"))
        self.action_save.setText(_translate("MainWindow", "Save"))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_clear.setText(_translate("MainWindow", "Clear"))
        self.action_clear.setToolTip(_translate("MainWindow", "Clear"))
        self.action_clear.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPalette_2.setText(_translate("MainWindow", "Palette 2"))
        self.actionPalette_2.setShortcut(_translate("MainWindow", "Alt+2"))
        self.actionPalette_1.setText(_translate("MainWindow", "Palette 1"))
        self.actionPalette_1.setShortcut(_translate("MainWindow", "Alt+1"))
        self.actionPalette_3.setText(_translate("MainWindow", "Palette 3"))
        self.actionPalette_3.setShortcut(_translate("MainWindow", "Alt+3"))
        self.actionPalette_4.setText(_translate("MainWindow", "Palette 4 "))
        self.actionPalette_4.setShortcut(_translate("MainWindow", "Alt+4"))
        self.actionPalette_5.setText(_translate("MainWindow", "Palette 5"))
        self.actionPalette_5.setShortcut(_translate("MainWindow", "Alt+5"))
        self.actionSave_as_PDF.setText(_translate("MainWindow", "Save as PDF"))
        self.actionSave_as_PDF.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.InputCh.setText(_translate("MainWindow", "InputChannel"))
        self.InputCh.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.ISpectroCh.setText(_translate("MainWindow", "InputSpectroChannel"))
        self.ISpectroCh.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.OutputCh.setText(_translate("MainWindow", "OutputChannel"))
        self.OutputCh.setShortcut(_translate("MainWindow", "Ctrl+3"))
        self.OSpectroCh.setText(_translate("MainWindow", "OutputSpectroChannel"))
        self.OSpectroCh.setShortcut(_translate("MainWindow", "Ctrl+4"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionClose.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actiontemp.setText(_translate("MainWindow", "temp"))
        self.actiontemp.setShortcut(_translate("MainWindow", "Alt+6"))

from pyqtgraph import PlotWidget
import img_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

